include:
  - project: cloudnative/gitlab/gitlabci/kaniko-image-ci
    ref: v1.X
    file: .kaniko.gitlab-ci.yml

stages:
  - version
  - build
  - scan
  - push
  - tag

trivy:
  allow_failure: true

variables:
  DOCKERFILE: "./Dockerfile"
  IMAGE_REPOSITORY: artifactory.cloud.statcan.ca/docker/platform/argocd
